############################################################
# Dockerfile to run default container
# Based on Ubuntu Image
############################################################

# Set the base image to use to Ubuntu
# VERSION 1
FROM ubuntu

# Set the file maintainer (your name - the file's author)
MAINTAINER Milan Karalic mixacha@gmail.com

RUN apt-get update

